var Countries = {
"AT" : "Austria",
"BE" : "Belgium",
"BG" : "Bulgaria",
"CY" : "Cyprus",
"CZ" : "Czech Republic",
"DE" : "Germany",
"DK" : "Denmark",
"EA17" : "Eurozone, 17 countries",
"EA18" : "Eurozone, 18 countries",
"EE" : "Estonia",
"EL" : "Greece",
"ES" : "Spain",
"EU27" : "All of Europe",
"FI" : "Finland",
"FR" : "France",
"HU" : "Hungary",
"IE" : "Ireland",
"IS" : "Iceland",
"IT" : "Italy",
"LT" : "Lithuania",
"LU" : "Luxembourg",
"LV" : "Latvia",
"MK" : "Macedonia",
"MT" : "Malta",
"NL" : "the Netherlands",
"NO" : "Norway",
"PL" : "Poland",
"PT" : "Portugal",
"RO" : "Romania",
"SE" : "Sweden",
"SI" : "Slovenia",
"SK" : "Slovakia",
"TR" : "Turkey",
"UK" : "United Kingdom",
"US" : "United States",
"HR" : "Croatia"
}